name: Divvun Actions
description: Actions runner for Divvun
author: https://github.com/divvun
requirements: []
configuration:
  properties:
    config:
      type: [string, object]
      additionalProperties: true
  additionalProperties: false
