name: Divvun Actions
description: Actions runner for Divvun
author: https://github.com/divvun
requirements: []
configuration:
  properties:
    type:
      type: string
      enum: [yaml, toml, json]
    setup:
      type: [string, object]
      additionalProperties: true
  additionalProperties: false
