import { defineImage } from "../lib/image.ts"
import {
  alpineSysroot,
  b3sum,
  clangSymlinks,
  gh,
  gitLfsInit,
  minisign,
  mkdir,
  openbao,
  pahkatUploader,
  rust,
} from "../tools/mod.ts"
import { versions } from "../versions.ts"

/** Packages used both in the host rootfs and the aarch64 cross-sysroot. */
const ALPINE_PACKAGES = [
  "autoconf",
  "automake",
  "bash",
  "boost-dev",
  "build-base",
  "bison",
  "ca-certificates",
  "clang21",
  "clang21-dev",
  "clang21-extra-tools",
  "clang21-static",
  "cmake",
  "compiler-rt",
  "curl",
  "deno",
  "flex",
  "git",
  "git-lfs",
  "icu-static",
  "jq",
  "libarchive-tools",
  "libc++-dev",
  "libc++-static",
  "llvm-libunwind-static",
  "libtool",
  "linux-headers",
  "lld21",
  "llvm21",
  "llvm21-dev",
  "make",
  "ninja",
  "openssh",
  "openssl-dev",
  "patch",
  "patchelf",
  "perl",
  "pkgconf",
  "protobuf",
  "python3",
  "rsync",
  "sqlite-dev",
  "tree",
  "unzip",
  "uv",
  "xz-dev",
  "xz-static",
  "zlib-dev",
  "zlib-static",
]

export default defineImage({
  target: "alpine",
  imageRef: "ghcr.io/divvun/divvun-actions:alpine-latest",
  base: "buildkite/agent:alpine",
  platform: "alpine",
  env: {
    BUILDKITE_PLUGIN_FS_CACHE_FOLDER: "/var/cache/buildkite",
  },
  apkRepositories: [
    `https://dl-cdn.alpinelinux.org/alpine/v${versions.alpine}/main`,
    `https://dl-cdn.alpinelinux.org/alpine/v${versions.alpine}/community`,
  ],
  apkPackages: ALPINE_PACKAGES,
  tools: [
    clangSymlinks({ version: versions.llvm }),
    rust({
      targets: [
        "x86_64-unknown-linux-musl",
        "aarch64-unknown-linux-musl",
      ],
    }),
    b3sum(),
    alpineSysroot({ arch: "aarch64", packages: ALPINE_PACKAGES }),
    openbao(),
    gh(),
    minisign(),
    pahkatUploader(),
    gitLfsInit(),
    mkdir({
      path: "$BUILDKITE_PLUGIN_FS_CACHE_FOLDER",
      label: "Buildkite fs-cache folder",
    }),
  ],
  copy: [{ src: "entrypoint-alpine.sh", dest: "/entrypoint.sh", chmod: true }],
  entrypoint: "/entrypoint.sh",
})
