import { defineImage } from "../lib/image.ts"
import {
  androidSdk,
  aptRepo,
  arm64UbuntuCross,
  awsCli,
  b3sum,
  clangSymlinks,
  deno,
  divvunRuntime,
  dockerAptRepo,
  gh,
  gitLfsInit,
  kbdgen,
  libtorch,
  minisign,
  mkdir,
  muslCross,
  nodejs,
  openbao,
  pahkatUploader,
  pipxInstall,
  rcodesign,
  rust,
  thfstTools,
  ubuntuFinnishMirrorWithApertium,
  uv,
  vulkanSdk,
} from "../tools/mod.ts"
import { versions } from "../versions.ts"

const LLVM = versions.llvm

const CLANG_PACKAGES = [
  `clang-${LLVM}`,
  `clang-format-${LLVM}`,
  `clang-tidy-${LLVM}`,
  `clang-tools-${LLVM}`,
  `clangd-${LLVM}`,
  `libc++-${LLVM}-dev`,
  `libc++1`,
  `libc++abi-${LLVM}-dev`,
  `libc++abi1`,
  `libclang-${LLVM}-dev`,
  `libunwind-${LLVM}-dev`,
  `lld-${LLVM}`,
  `lldb-${LLVM}`,
  `llvm-${LLVM}`,
  `llvm-${LLVM}-dev`,
  `llvm-${LLVM}-runtime`,
  `python3-clang-${LLVM}`,
]

const TAURI_GTK_PACKAGES = [
  "libwebkit2gtk-4.1-dev",
  "libgtk-3-dev",
  "libayatana-appindicator3-dev",
  "librsvg2-dev",
]

export default defineImage({
  target: "linux",
  imageRef: "ghcr.io/divvun/divvun-actions:ubuntu-latest",
  base: "buildkite/agent:3-ubuntu-24.04",
  platform: "ubuntu",
  shell: "bash-lic",
  env: {
    BUILDKITE_PLUGIN_FS_CACHE_FOLDER: "/var/cache/buildkite",
    ANDROID_HOME: "/root/Android/sdk",
    ANDROID_NDK_HOME: `/root/Android/sdk/ndk/${versions.ndk}`,
  },
  aptPackages: [
    // Build essentials & general dev tools
    "apertium-all-dev",
    "bc",
    "bison",
    "build-essential",
    "ca-certificates",
    "cmake",
    "containerd.io",
    "curl",
    "divvun-gramcheck",
    "docker-buildx-plugin",
    "docker-ce",
    "docker-ce-cli",
    "docker-compose-plugin",
    "flex",
    "git-lfs",
    "imagemagick",
    "just",
    "libarchive-tools",
    "libboost-all-dev",
    "libicu-dev",
    "libicu74",
    "libsqlite3-dev",
    "libssl-dev",
    "ninja-build",
    "openjdk-17-jdk",
    "osslsigncode",
    "patchelf",
    "pipx",
    "pkg-config",
    "protobuf-compiler",
    "python3-gtgramtools",
    "python3-gtmorphtest",
    "rsync",
    "socat",
    "tree",
    "unzip",
    ...CLANG_PACKAGES,
    ...TAURI_GTK_PACKAGES,
  ],
  // Run BEFORE the big apt install so third-party packages (LLVM, Kitware cmake,
  // Docker, apertium, divvun) are available for resolution.
  preInstall: [
    ubuntuFinnishMirrorWithApertium(),
    aptRepo({
      name: "LLVM",
      keyUrl: "https://apt.llvm.org/llvm-snapshot.gpg.key",
      keyring: "/usr/share/keyrings/llvm-archive-keyring.gpg",
      sourceLine:
        `deb [signed-by=/usr/share/keyrings/llvm-archive-keyring.gpg] http://apt.llvm.org/noble/ llvm-toolchain-noble-${LLVM} main`,
      list: "llvm.list",
    }),
    aptRepo({
      name: "Kitware (cmake)",
      keyUrl: "https://apt.kitware.com/keys/kitware-archive-latest.asc",
      keyring: "/usr/share/keyrings/kitware-archive-keyring.gpg",
      sourceLine:
        `deb [signed-by=/usr/share/keyrings/kitware-archive-keyring.gpg] https://apt.kitware.com/ubuntu/ noble main`,
      list: "kitware.list",
      update: true,
    }),
    dockerAptRepo(),
  ],
  tools: [
    androidSdk(),
    clangSymlinks({ version: LLVM }),
    arm64UbuntuCross(),
    muslCross({ arch: "x86_64" }),
    muslCross({ arch: "aarch64" }),
    uv(),
    pipxInstall({
      spec: "git+https://github.com/divvun/GiellaLTLexTools",
      label: "GiellaLTLexTools (gtlemmatest, gtspelltest, ...)",
      exportPath: true,
    }),
    gh(),
    rust({
      targets: [
        "aarch64-linux-android",
        "armv7-linux-androideabi",
        "x86_64-linux-android",
      ],
      gitInstalls: [
        { name: "cross", url: "https://github.com/cross-rs/cross" },
      ],
      binstall: ["just", "cargo-ndk"],
    }),
    b3sum(),
    nodejs(),
    deno(),
    libtorch(),
    openbao(),
    pahkatUploader(),
    kbdgen(),
    thfstTools(),
    awsCli(),
    divvunRuntime(),
    minisign(),
    rcodesign(),
    vulkanSdk(),
    gitLfsInit(),
    mkdir({
      path: "$BUILDKITE_PLUGIN_FS_CACHE_FOLDER",
      label: "Buildkite fs-cache folder",
    }),
  ],
  copy: [{ src: "entrypoint.sh", dest: "/entrypoint.sh", chmod: true }],
  entrypoint: "/entrypoint.sh",
})
