import { defineImage } from "../lib/image.ts"
import {
  awsCli,
  bsdtarWindows,
  buildkiteAgentWindows,
  chocoInstall,
  chocolatey,
  clearPathDuplicates,
  cmakeWindows,
  createPowershellProfile,
  deno,
  dockerCliWindows,
  envVars,
  gh,
  gitForWindows,
  innoSetup,
  justWindows,
  kbdgen,
  mkdir,
  msklc,
  msvcEnv,
  msys2,
  ninjaWindows,
  nodejsWindows,
  openbao,
  opensshWindows,
  pahkatUploader,
  raw,
  rust,
  setUser,
  sshAgentService,
  uv,
  vcpkg,
} from "../tools/mod.ts"

export default defineImage({
  target: "windows",
  imageRef: "ghcr.io/divvun/divvun-actions:windows-latest",
  base: "ghcr.io/divvun/lts-windowsservercore-ltsc2022-vs2022:latest",
  baseStage: "buildkite-agent",
  platform: "windows",
  shell: "pwsh",
  tools: [
    gitForWindows(),
    buildkiteAgentWindows(),
    chocolatey(),
    innoSetup(),
    msklc(),
    cmakeWindows(),
    raw(
      "Create C:\\bin",
      [
        `RUN New-Item -ItemType Directory -Path C:\\bin ; \\`,
        `    setx /M PATH $('C:\\bin;' + $Env:PATH)`,
      ].join("\n"),
    ),
    ninjaWindows(),
    openbao(),
    bsdtarWindows(),
    chocoInstall({ package: "osslsigncode" }),
    msys2(),
    msvcEnv(),
    sshAgentService(),
    setUser("ContainerAdministrator"),
    nodejsWindows(),
    rust({ targets: ["aarch64-pc-windows-msvc"] }),
    deno(),
    pahkatUploader(),
    awsCli(),
    justWindows(),
    kbdgen(),
    dockerCliWindows(),
    gh(),
    uv(),
    opensshWindows(),
    vcpkg(),
    envVars("Buildkite fs-cache folder", {
      BUILDKITE_PLUGIN_FS_CACHE_FOLDER: "C:\\buildkite-cache",
    }),
    mkdir({
      path: "$env:BUILDKITE_PLUGIN_FS_CACHE_FOLDER",
      label: "Create cache folder",
    }),
    clearPathDuplicates(),
    createPowershellProfile(),
  ],
})
