#!/bin/bash
set -ueo pipefail

PLUGIN_DIR=$(realpath $(dirname "${BASH_SOURCE[0]}")/..)

# Ensure main isn't kept stale
if [[ "$PLUGIN_DIR" == *-main ]]; then
  git -C $PLUGIN_DIR checkout main
  git -C $PLUGIN_DIR pull
fi

export DIVVUN_ACTIONS_PLUGIN_DIR=$PLUGIN_DIR
export PATH="$PLUGIN_DIR/bin:$PATH"

if [[ "$(uname)" == "Darwin" ]]; then
  # Ensure that the PATH is set correctly for macOS
  export PATH="/opt/homebrew/opt/coreutils/libexec/gnubin:$PATH"
fi

echo "Bash"
echo $PATH