#!/bin/sh
SYSROOT="/opt/sysroot-aarch64"
MUSL_TARGET="aarch64-linux-musl"

exec clang++ \
    --target=${MUSL_TARGET} \
    --sysroot=${SYSROOT} \
    -resource-dir=${SYSROOT}/usr/lib/llvm21/lib/clang/21 \
    -isystem ${SYSROOT}/usr/include/c++/v1 \
    -isystem ${SYSROOT}/usr/include \
    -isystem /usr/lib/llvm21/lib/clang/21/include \
    -stdlib=libc++ \
    --rtlib=compiler-rt \
    --unwindlib=libunwind \
    -Wno-unused-command-line-argument \
    "$@"
