import type { Platform, RenderCtx, ShellKind } from "./platform.ts"
import { dockerfileShellDirective } from "./platform.ts"

export type Tool = {
  /** Short identifier used for the comment header above the emitted directives. */
  name: string
  render(ctx: RenderCtx): string
}

export type CopyDirective = { src: string; dest: string; chmod?: boolean }

export type ImageDef = {
  target: string
  /** Full registry reference (e.g. `ghcr.io/divvun/divvun-actions:alpine-latest`). */
  imageRef: string
  base: string
  /** Optional `AS <stage>` name on the FROM directive. */
  baseStage?: string
  platform: Platform
  /**
   * Shell used for RUN directives. When omitted, no SHELL directive is
   * emitted and Docker's default (`/bin/sh -c` on linux, `cmd /S /C` on
   * windows) applies. Tools still render their own line syntax based on
   * the platform (POSIX `&&` joiners for linux, `;` for pwsh).
   */
  shell?: ShellKind
  /** `# escape=...` for the windows backtick escape char. */
  escape?: "`" | "\\"
  env?: Record<string, string>
  /** Optional USER directive appearing after package installation. */
  user?: string
  /**
   * Tools emitted *before* the batched apt/apk install — for apt-repo
   * setup, mirror swaps, architecture enablement, and other steps that
   * need to run before packages are resolved.
   */
  preInstall?: Tool[]
  /** apt packages installed in one batched RUN (linux/ubuntu images). */
  aptPackages?: string[]
  /** apk packages installed in one batched RUN (alpine images). */
  apkPackages?: string[]
  /**
   * apk repo URLs written to /etc/apk/repositories **before** the apk add.
   * Replaces the default file with exactly these lines.
   */
  apkRepositories?: string[]
  /** Tools rendered in order. */
  tools: Tool[]
  copy?: CopyDirective[]
  entrypoint?: string
  /** Raw lines emitted at the very end, after ENTRYPOINT. Escape hatch. */
  rawTail?: string[]
}

export function defineImage(def: ImageDef): ImageDef {
  return def
}

const GENERATED_HEADER = [
  "# ──────────────────────────────────────────────────────────────────────────",
  "# Generated by docker/generate.ts — DO NOT EDIT.",
  "# Edit docker/images/*.ts or docker/tools/*.ts, then run `deno task docker:gen`.",
  "# ──────────────────────────────────────────────────────────────────────────",
]

export function renderImage(def: ImageDef): string {
  const ctx: RenderCtx = {
    platform: def.platform,
    shell: def.shell ?? (def.platform === "windows" ? "cmd" : "bash-lic"),
  }
  const out: string[] = []

  if (def.escape) out.push(`# escape=${def.escape}`)
  out.push(...GENERATED_HEADER)
  out.push("")
  const fromLine = def.baseStage
    ? `FROM ${def.base} AS ${def.baseStage}`
    : `FROM ${def.base}`
  out.push(fromLine)
  out.push("")

  if (def.shell) {
    const shellArr = dockerfileShellDirective(def.shell)
    out.push(`SHELL [${shellArr.map((s) => JSON.stringify(s)).join(", ")}]`)
    out.push("")
  }

  if (def.env) {
    for (const [k, v] of Object.entries(def.env)) {
      out.push(`ENV ${k}=${JSON.stringify(v)}`)
    }
    out.push("")
  }

  if (def.apkRepositories && def.apkRepositories.length > 0) {
    const lines = def.apkRepositories.map((repo, i) => {
      const redirect = i === 0 ? ">" : ">>"
      return `echo "${repo}" ${redirect} /etc/apk/repositories`
    })
    out.push(`# Configure apk repositories`)
    out.push(`RUN ${lines.join(" && \\\n    ")}`)
    out.push("")
  }

  if (def.preInstall) {
    for (let i = 0; i < def.preInstall.length; i++) {
      const tool = def.preInstall[i]
      out.push(`# ${tool.name}`)
      out.push(renderTool(def.target, "preInstall", i, tool, ctx))
      out.push("")
    }
  }

  if (def.apkPackages && def.apkPackages.length > 0) {
    const pkgs = def.apkPackages.map((p) => `    ${p}`).join(" \\\n")
    out.push(`# System packages (apk)`)
    out.push(`RUN apk update && apk upgrade && apk add --no-cache \\`)
    out.push(pkgs)
    out.push("")
  }

  if (def.aptPackages && def.aptPackages.length > 0) {
    const pkgs = def.aptPackages.map((p) => `    ${p}`).join(" \\\n")
    out.push(`# System packages (apt)`)
    out.push(`RUN apt-get update && \\`)
    out.push(`    DEBIAN_FRONTEND=noninteractive apt-get install -y \\`)
    out.push(pkgs + ` && \\`)
    out.push(`    rm -rf /var/lib/apt/lists/* && apt-get clean`)
    out.push("")
  }

  for (let i = 0; i < def.tools.length; i++) {
    const tool = def.tools[i]
    out.push(`# ${tool.name}`)
    out.push(renderTool(def.target, "tools", i, tool, ctx))
    out.push("")
  }

  if (def.user) {
    out.push(`USER ${def.user}`)
    out.push("")
  }

  if (def.copy) {
    for (const c of def.copy) {
      out.push(`COPY ${c.src} ${c.dest}`)
      if (c.chmod) out.push(`RUN chmod +x ${c.dest}`)
    }
    if (def.copy.length > 0) out.push("")
  }

  if (def.entrypoint) {
    out.push(`ENTRYPOINT ${JSON.stringify([def.entrypoint])}`)
    out.push("")
  }

  if (def.rawTail) {
    out.push(...def.rawTail)
    out.push("")
  }

  return out.join("\n").replace(/\n{3,}/g, "\n\n").trimEnd() + "\n"
}

function renderTool(
  target: string,
  section: "tools" | "preInstall",
  index: number,
  tool: Tool,
  ctx: RenderCtx,
): string {
  try {
    return tool.render(ctx)
  } catch (err) {
    const msg = err instanceof Error ? err.message : String(err)
    throw new Error(
      `[image ${target} / ${section}[${index}] "${tool.name}"] ${msg}`,
      { cause: err instanceof Error ? err : undefined },
    )
  }
}
